name: master
description: A new Flutter project made by Asafe.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  http: ^0.13.3
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  form_field_validator: ^1.1.0
  shared_preferences: ^2.0.7
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  flutter_modular_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/env/
    - lib/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: lib/assets/fonts/poppins/Poppins-ExtraLight.ttf
         - asset: lib/assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
#         - asset: lib/assets/fonts/poppins/Poppins-Thin.ttf
#         - asset: lib/assets/fonts/poppins/Poppins-ThinItalic.ttf
           style: normal
           weight: 700

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

scripts:
  dev: flutter run lib/dev_main.dart
  dev-debug: flutter run lib/dev_main.dart --debug
  hom: flutter run lib/hom_main.dart
  hom-debug: flutter run lib/hom_main.dart --debug
  prod: flutter run lib/prod_main.dart
  prod-debug: flutter run lib/prod_main.dart --debug

#  mobx
  watch: flutter packages pub run build_runner watch
  clean: flutter packages pub run build_runner watch --delete-conflicting-outputs
  build: flutter packages pub run build_runner build

